server {
    listen 80;
    server_name admin.152.32.172.162.sslip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}
